### ISSUE TITLE
धनप्रश्नः

### ISSUE THREAD

**Issue by vvasuki** [avinashvarna/sanskrit_tts#1]
नमामि भोः, एतच्चालयितुं कियद्धनं गूगलाय देयं स्याद् इति परिचयपत्रे प्रकाशयतु - यतो यदि निश्शुल्कं बहु ध्वनिम् उत्पादयितुं शक्यम्, प्रयुञ्जीय।

**Comment by avinashvarna** [comment]
README मध्ये link वर्तत एव :
> Note that the TTS API will incur a cost if the free quota is exceeded ([details](https://cloud.google.com/text-to-speech/pricing)). The library uses a wavenet voice by default, but this can be changed via the voice parameter to [synthesize_text](https://github.com/avinashvarna/sanskrit_tts/blob/main/sanskrit_tts/gcloud_tts.py#L56).

TLDR - Default Wavenet voice - प्रतिमासम् १M characters निश्शुलकम् । तदनु $16/1M characters. Non-wavenet voice - 4M characters free, $4/4M characters. (Note: characters includes spaces).

प्रायेण अल्पमूल्यमेव । प्रतिमासं ध्वनिम् उत्पादय ! कस्य मूलस्य उत्पादयितुम् इच्छति ? द्वित्रैः गणरूपेण क्रियते चेत् निश्शुल्कं साधयितुं शक्यं स्यात् ।

**Comment by avinashvarna** [comment]
https://www.ragavera.com/contact-us एतेषामपि संपर्कं कृत्वा तेषां [तन्त्रांशस्य](https://www.ragavera.com/tts/sg-kan-samples) कियत् मूल्यम् इति प्रष्टुम् अर्हामः ।

**Comment by vvasuki** [comment]
आह् - रुचिरम्। पृष्टं विपत्रेण। सूत्रं समाहितम् पिदधामि।
