### ISSUE TITLE
No such attribute

### ISSUE THREAD

**Issue by julkamny** [avinashvarna/sanskrit_tts#6]
Hello,

Thank you for this module! I am trying to use it but keep getting the following error : 

module 'sanskrit_tts.gcloud_tts' has no attribute 'synthesize_text'. 

Changing "audio = gcloud_tts.synthesize_text(text)" to "audio = gcloud_tts.synthesize(text)" yields the same result. Could there be something wrong in the code of simple_example.ipynb? Would you be so kind as to take the time to help me?

Best,
J.

**Comment by avinashvarna** [comment]
Hello,

Thank you for your interest in this module. We recently updated it to add
support for another TTS engine and made some changes in the process.
Unfortunately, I forgot to update the Readme and the example. Please give
me a few days to update them.

Thanks

**Comment by avinashvarna** [comment]
Hi @julkamny 

Please take a look at the Usage section in the Readme - https://github.com/avinashvarna/sanskrit_tts#usage. If you run into any trouble, then please reopen this issue.

Thanks
